.gitignore
lib/operation.ts
lib/options.ts
ng-openapi-gen-schema.json
package-lock.json
package.json

This functionality is very useful when you have interceptors in the angular app for some headers like  `Tenant-Code` or `X-Authorization` and dont need to pass it to the service methods.
[Angular Interceptors Documentation](https://angular.io/guide/http#intercepting-requests-and-responses)

 Add excludeParameters functionality

---

lib/operation.ts
lib/security.ts
lib/service.ts
templates/operationResponse.handlebars

Currently, security information in the openApi file is not being parsed by the generator. Instead the documentation just recommends using HTTP interceptors.
Added basic parsing of the security schema into operations object for use in templates. I didn't add the security to the template as this will require more thought on how best to handle and may be best left to custom templates.

feat: parse security

---

README.md
templates/module.handlebars

Remove HTTPClientModule and replace with a constructor check.
HTTPClientModule should only be declared once in a project. By removing the import and replacing with a constructor check, there is more flexibility in the import structure of the module.
HttpClientModule no imported by the module

fix: remove HttpClientModule

---

templates/module.handlebars

In case user overrides module option in config file, he or she generates incorrect module file because it refers to default module name (ApiModule), that doesn't exist in updated module. I updated the template to reflect overridden config parameter

Use config-provided module name in module template

---

lib/ng-openapi-gen.ts
lib/options.ts
ng-openapi-gen-schema.json
templates/index.handlebars

The index file exports all generated files. This is useful when working with NX and libs.

feature: adds parameter to generate an index file

---

lib/operation.ts
test/all-operations.json
test/all-operations.spec.ts

This PR adds support for reusable responses ($ref) as described in:
- https://swagger.io/docs/specification/describing-responses/
- https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#responses-object
Unit tests added to cover the new functionality.
Bye and thanks for this great lib!

Add support for $ref in responses

---

lib/ng-openapi-gen.ts

Error on API generation from xxx.json: Error: ENOTEMPTY: directory not empty, rmdir 'xxx/api$' #94 
Was actually an issue in rimraf: https://github.com/isaacs/rimraf/issues/25
Used a different approach that should work in windows: https://stackoverflow.com/questions/18052762/remove-directory-which-is-not-empty/32197381

Delete temp folder windows fix

---

lib/parameter.ts
templates/operationResponse.handlebars

Parameter options are created in `parameter.ts`, but are never actually used in `operationResponse.handlebars`, resulting in parameters of deepObject style being sent to servers incorrectly. The changes below fix this by adding `parameterOptions` to the request builder query parameters.
Changes to `parameter.ts` are crucial, as handlebars is unfortunately unable to output the stringified JSON using a getter.

OpenAPI parameter options are not used in services

---

templates/operationParameters.handlebars
templates/operationResponse.handlebars

- Remove blank lines in the operationParameters when an endpoint does not have either params, a body or both
- Remove the double indentation for the body param
- Remove the blank lines in the if(params) block in the operationResponse
- Add a blank line between the if(params) block and the request block

Update operation whitespacing

---

lib/parameter.ts
test/all-operations.json
test/all-operations.spec.ts
test/parameter.spec.ts

When explode is set to false in openApi, the Parameter class is never handling that because of the `if (this.explode)`. As `explode` is `true` by default, the requestBuilder is never executing the specific logic implemented in case of `explode=false`.
This PR solves that issue.

Fix explode false condition

---

lib/gen-utils.ts
test/all-operations.json
test/all-operations.spec.ts

Tags are sliced only by the first dot that prevents create nested directory structure more than 2 levels deep.
This pr fix #133

Fix tags parsing into namespaces

---

lib/gen-utils.ts
test/all-types.spec.ts

I did an attempt at merging all of PR-110 but I was unable to resolve the diff with master on my own. Instead I cherry-picked the solution for #111 to try and see if we can merge the solution for #111 separately. I did wonder how much of a problem the, in some cases unnecessary, parenthesis are as demonstrated by the changed tests?

Attempt to fix operator precedence based on PR-110

---

lib/operation-variant.ts

The inferResponseType checks for ending of the media type:  
```
if (mediaType.endsWith('/json') || mediaType.endsWith('+json')) {
```
But it's quite usual to have it like this:
```
content:
application/json; charset=utf-8:
...
```
Which breaks the inference and makes the responseType to be "blob".
**Proposed solution:**
It's enough for media type to _include_ the "/json" and "+json" strings, not _endsWith_.

Support json media types with charset

---

lib/cmd-args.ts
package-lock.json
package.json

Should fix issue #168.
Had to also upgrade the typings for argparse, as the current version doesn't support the actual argparse 2.0.1 syntax
Line 62 is questionable. I didn't want to rewrite the rest of the function to stay as consistent to your style as possible. That's why I chose to just typecast the argument to make typescript shut up. Not elegant, but it seems to work correctly, pass the tests and show the correct help message.

Migrated to the new argparse v2 syntax

---

templates/requestBuilder.handlebars
test/mock/request-builder.ts
test/request-builder.spec.ts

Javascript replace only acts on the first found match if the pattern is
a string. Change the patterns to regular expressions and use the global
flag to ensure all occurrences are replaced.
This also updates the test to include some checks around the three
special characters we un-escape in this code.
We noticed this with CodeQL Security Scanning on our repository- this rule was tripped: https://github.com/github/codeql/blob/56786790fcf88b79d1d26b946ff36dfe2d6f33ac/javascript/ql/src/Security/CWE-116/IncompleteSanitization.ql

Ensure all occurrences are replaced in path parameter sanitization

---

README.md
package.json

This makes it possible to to not only use the cli but call the generator directly from within custom build scripts. This is useful for more complex setups and does not harm the existing cli functionality.

give direct access to the generator

---

lib/ng-openapi-gen.ts
lib/options.ts
lib/templates.ts
ng-openapi-gen-schema.json
test/templates.spec.ts

Closes #198 
As suggested by maximebochon I added a new configuration option "endOfLineStyle" having the default value set to 'auto' (same behavior as before). I removed the eol import from template.ts because it only had overridden the template itself without the provided data. That's why I implemented it in the ng-openapi-gen.ts

feat: added config option for EOL

---

README.md
package.json
templates/operationParameters.handlebars
templates/operationResponse.handlebars
templates/requestBuilder.handlebars
templates/service.handlebars
test/petstore.spec.ts

Fixes https://github.com/cyclosproject/ng-openapi-gen/issues/160
Please note that it requires Angular12+

Add HttpContext support for Angular 12+ apps.

---

lib/ng-openapi-gen.ts
lib/options.ts
ng-openapi-gen-schema.json
test/useTempDir.config.json
test/useTempDir.json
test/useTempDir.spec.ts

As I suggested in #218 here's a PR for adding an option to use system temporary directory instead of the output directory.
I have noticed a large VSCode workspace may use a lot of CPU when a lot of files are created/deleted and VSCode wants to index the files for its search.
The benefit of this would be that the `tempDir` and all its files would not affect the workspace or repository for the code that other applications may use and react to. As earlier, only the affected files will be copied/deleted from the final output directory so the output directory changes would be limited to the changes that ng-openapi-gen detects and copies to the final output directory.
- The option `useTempDir` was added to schema and options.ts
- The function `initTempDir` in ng-openapi-gen.ts to use system …

Option to use system temporary directory

---

lib/gen-utils.ts
lib/logger.ts
lib/ng-openapi-gen.ts
lib/operation.ts
lib/options.ts
ng-openapi-gen-schema.json

This adds an option "silent". If it is set to `true` not console messages (info, log, debug) are shown.
This is very useful if you call the generator from within another script.

feature: adds "silent" option to reduce console output

---

lib/gen-utils.ts
test/polymorphic.json
test/polymorphic.spec.ts

Adds support for discriminator properties on derived types when used in conjuction with oneOf + allOf.
Fixes #227

added support for explicit discriminator values on derived types

---

lib/model.ts

Models with namespaces that have references between each other are broken since v0.50.
This is a simple openapi 3 definition with a model named "Ns.Ns2.Customer" referencing another one named "Ns.Address":
[openapi.json.txt](https://github.com/cyclosproject/ng-openapi-gen/files/12464071/openapi.json.txt)
The import to Customer in the API service is modeled correctly:
`import { Customer as NsNs2Customer } from '../models/Ns/Ns2/customer';`
However, the import from Customer to Address is broken:
`import { Address as NsAddress } from '..//../models/Ns/address';`
From what I found:
1. in lib/model.ts "pathToModels" creates the double "//" as it joins "../" with a "/"
2. in lib/imports.ts "add" seems to introduce the "models"
My idea (in this PR):
1. Remove the "/" in join of pathToModels
2. …

Fix model import with namespaces

---

lib/ng-openapi-gen.ts
lib/options.ts
test/filterPaths.spec.ts

A draft should be able to fix https://github.com/cyclosproject/ng-openapi-gen/issues/279
Please kindly check if it looks OK to you  @luisfpg  
If yes I will continue to add content in README.md and maybe some more refinement(like allowing user to inject their own filter logic )  
Thank you.

Fix #279  Exclude API definitions with by matching the API path 

---

lib/operation.ts
lib/options.ts
ng-openapi-gen-schema.json
test/all-operations.config.json
test/all-operations.json
test/all-operations.spec.ts

I started to use your project to generate my Angular client, but soon stumbled on the problem described in #183, so I offer an opt-in solution here.
I added the option `keepFullResponseMediaType`, where one can choose which media type should be shortened to `$Json` or which should be kept in whole.
Specifically, when true, the expected response type in the request method names are not abbreviated and all response variants are kept.
When array is given, `mediaType` is expected to be a RegExp string matching the response media type. The first match in the array
will decide whether or how to shorten the media type. If no mediaType is given, it will always match.
| option value | media type | variant method name |
|-----|---|---|
| short |     application/x-spring-data-compact+json    | …

Adds option to maintain different media types of one one response type

---

templates/index.handlebars
test/all-types.spec.ts
test/noModule.config.json
test/noModule.json
test/noModule.spec.ts

See #337 
We might not want a module but still want an index, e.g.:
```json
{
"module": false,
"indexFile": true
}
```
In such a case, we'd get something like:
```typescript
/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
export { ApiConfiguration } from './api-configuration';
export { BaseService } from './base-service';
export { RequestBuilder } from './request-builder';
export { StrictHttpResponse } from './strict-http-response';
export {  } from './';   // <----------------------------------------- Note this broken export
export { ApiService } from './services/api.service';
```
Guard the export in the template. Be sure to not break things by writing tests for the exports in `index.ts` for both cases - whenever `module` is on or off. …

Do not emit an empty module export in the index if no module is required

---

lib/gen-utils.ts
test/const.config.json
test/const.json
test/const.spec.ts

Since the base TypeScript Types of @loopback/openapi-v3-types are fairly outdated, the don't contain "const". I think it would be best to inline those entirely, but that's another project.
So here I just use dirty `any`.

Support const
